### ISSUE TITLE
RequireDbContextHandler should allow custom logic to decide commit/rollback

### ISSUE THREAD

**Issue by samuelpsfung** [tlyau62/UnityAddon3#2]
now,
method return = success = commit
method throw ex = failure = rollback

some app may return bool or ActionResult to mean success/failure, the Addon should honour this custom logic to decide commit/rollback.

**Comment by tlyau62** [comment]
Added at commit 3ba71629e2b8fa67bbbc9570f9d9e8cbe35b6ec1
